### ISSUE TITLE
Documentation: Readme missing an instruction

### ISSUE THREAD

**Issue by ghost** [joshuajnoble/ofxKinectCommonBridge#24]
Under "project generator Help" in README.md, the section for adding additional library directories is incomplete.  It needs to include the following directory:

$(KINECTSDK10_DIR)\lib\x86

Without that directory the linker cannot find Kinect10.lib

**Comment by birbilis** [comment]
> I am using the June SDK (KinectSDK-v2.0-DevPreview1406).

@microcosm do you happen to still have that installer? It seems it was the last one containing KinectFirmwareUpdate tool. I have issue with automatic firmware update failing in newer Kinect SDK and my Kinect v2 having remained in a state where it always restarts

**Comment by microcosm** [comment]
I don't have it - good luck with fixing your Kinect.
