### ISSUE TITLE
KinectCommonBridgle.dll is missing

### ISSUE THREAD

**Issue by paul-ferragut** [joshuajnoble/ofxKinectCommonBridge#36]
After it compiles on start up I got a System error window 'The program can't start because KinectCommonBridge.dll is missing from your computer. Try reinstalling the program to fix this problem.'
In solution manager > Linker > Input > additional dependencies
I tried to remove KinectCommonBridge.dll but no success.

**Comment by paul-ferragut** [comment]
the missing KinectCommonBridge.dll was copied in a folder 'vs' in bin. Manually copying it into bin solved the issue

**Comment by bbcollinsworth** [comment]
Hi Paul - thanks for your solution to this. It enabled me to run ofxKinectCommonBridge in VS2012 debug mode (after about a week of pulling hair out). 

In release mode, however, I still get an error that seems to be related to this -- copied below. Building in debug mode and then running the "last successful build" in release works, so I'm using that as a workaround for the moment, but I'm wondering if you encountered this as well and have any more effective solutions...

Error	9	error MSB3073: The command "xcopy /e /i /y "C:\Users\bcoll_000\Desktop\oFVisualStudio\addons\ofxKinectCommonBridge\example-Skeleton\..\..\..\export\vs\*.dll" "C:\Users\bcoll_000\Desktop\oFVisualStudio\addons\ofxKinectCommonBridge\example-Skeleton\bin"
xcopy /e /i /y "C:\Users\bcoll_000\Desktop\oFVisualStudio\addons\ofxKinectCommonBridge\example-Skeleton\..\libs\KinectCommonBridge\lib\windows\x86\*.dll" "C:\Users\bcoll_000\Desktop\oFVisualStudio\addons\ofxKinectCommonBridge\example-Skeleton\bin"

:VCEnd" exited with code 4.

**Comment by minusplusminus** [comment]
replace xcopy line in Properties > Build Events > Post-Build Event with this:

xcopy /e /i /y "$(ProjectDir)..\..\..\export\vs\*.dll" "$(ProjectDir)bin"
xcopy /e /i /y "$(ProjectDir)..\libs\KinectCommonBridge\lib\windows\vs\*.dll" "$(ProjectDir)bin"
